name: varsha
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  file_selector: ^1.0.3
  shared_preferences: ^2.3.1
  nfc_manager: ^3.5.0
  provider: ^6.1.2
  ndef: ^0.3.4
  cloud_firestore: ^5.6.1
  firebase_core: ^3.10.0
  url_launcher: ^6.3.1
  qr_flutter: ^4.1.0
  easy_localization: ^3.0.0  
  cached_network_image: ^3.0.0  
  image_picker: ^0.8.5  
  firebase_storage: ^11.0.0 
  file_picker: ^8.3.1
  flutter_cached_pdfview: ^0.1.0  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/RAPIDX_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/translations/
    - assets/RAPIDX_logo.png
